<a href="https://colab.research.google.com/github/Rachev2002/sql/blob/main/sql_ex_postgres_in_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL-EX with Postgres



In [ ]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 10.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package cron.
(Reading database ... 123991 files and directories currently installed.)
Preparing to unpack .../0-cron_3.0pl1-128.1ubuntu1.2_amd64.deb ...
Unpacking cron (3.0pl1-128.1ubuntu1.2) ...
Selecting previously unselected package logrotate.
Preparing to unpack .../1-logrotate_3.11.0-0.1ubuntu1_amd64.deb ...
Unpacking logrotate (3.11.0-0.1ubuntu1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../2-netbase_5.4_all.deb ...
Unpacking netbase (5.4) ...
Selecting previously unselected

In [ ]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

Скачиваем данные с sql-ex

In [ ]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2022-11-29 06:57:00--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 5.188.73.5, 2a00:ab00:1203:22:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|5.188.73.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql’

sql-ex-pg.sql       100%[===================>]  40.09K  --.-KB/s    in 0s      

2022-11-29 06:57:01 (262 MB/s) - ‘sql-ex-pg.sql’ saved [41053/41053]



In [ ]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

Запускаем скрипт

In [ ]:
con.execute(sql[1:])

Сделаю еще свою знаменитую функцию select, которая заворачивает пандосовкую функцию. Нужно для того, чтобы каждый раз не писать всю эту авадакедавру, а писать красивенький селект

In [ ]:
import pandas as pd

In [ ]:
def select(sql):
  return pd.read_sql(sql,con)

# Задача 1

https://sql-ex.ru/exercises/index.php?act=learn&LN=1

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''select t.model, t.speed, t.hd from PC t
where t.price < 500
'''

In [ ]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

# Задача 2

https://sql-ex.ru/exercises/index.php?act=learn&LN=2


Найдите производителей принтеров. Вывести: maker

In [ ]:
sql = '''select * from Product'''

In [ ]:
select(sql)

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [ ]:
sql = '''select distinct p.maker from Product p
where p.type = 'Printer'
'''

In [ ]:
select(sql)

maker
0     A
1     D
2     E

# Задача 3

https://sql-ex.ru/exercises/index.php?act=learn&LN=3#resPlace

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
sql = '''select * from Laptop'''

In [ ]:
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [ ]:
sql = '''select t.model, t.ram, t.screen from Laptop t
where t.price > 1000
'''

In [ ]:
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

# Задача 4

https://sql-ex.ru/exercises/index.php?act=learn&LN=4

Найдите все записи таблицы Printer для цветных принтеров.

In [ ]:
sql = '''select * from Printer'''

In [ ]:
select(sql)

code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0
5     6  1288     n   Laser  400.0

In [ ]:
sql = '''select * from Printer t
where color = 'y'
'''

In [ ]:
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

# Задача 5

https://sql-ex.ru/exercises/index.php?act=learn&LN=5

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''select t.model, t.speed, t.hd from PC t
where (t.cd = '12x' or t.cd = '24x') and t.price < 600
'''

In [ ]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

# Задача 6

https://sql-ex.ru/exercises/index.php?act=learn&LN=6

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.

In [ ]:
sql = '''select distinct p.maker, l.speed from Product p
left join Laptop l on p.model = l.model
where type = 'Laptop' and hd >= 10
order by maker, speed

'''

In [ ]:
select(sql)

maker  speed
0     A    450
1     A    600
2     A    750
3     B    750

# Задача 7

https://sql-ex.ru/exercises/index.php?act=learn&LN=7

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [ ]:
sql = '''select * from Product'''

In [ ]:
select(sql)

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [ ]:
sql = '''

select distinct product.model, pc.price from Product 
join PC  on Product.model = PC.model 
where maker = 'B'

union

select distinct product.model, laptop.price from Product 
join laptop on product.model = laptop.model
where maker = 'B'

union 

select distinct product.model, printer.price from product 
join printer on product.model = printer.model
where maker = 'B';


'''

In [ ]:
select(sql)

model   price
0  1750  1200.0
1  1121   850.0

# Задача 8

https://sql-ex.ru/exercises/index.php?act=learn&LN=8


Найдите производителя, выпускающего ПК, но не ПК-блокноты.

In [ ]:
sql = '''select * from Product'''

In [ ]:
select(sql)

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [ ]:
sql = '''
SELECT DISTINCT maker
FROM product
WHERE type = 'pc'
EXCEPT
SELECT DISTINCT product.maker
FROM product
Where type = 'laptop'

'''

In [ ]:
select(sql)

Empty DataFrame
Columns: [maker]
Index: []

# Задача 9

https://sql-ex.ru/exercises/index.php?act=learn&LN=9

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [ ]:
sql = '''select * from Product '''

In [ ]:
select(sql)

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [ ]:
sql = '''select distinct maker from Product p
join PC on p.model = pc.model 
where pc.speed >= 450 
'''

In [ ]:
select(sql)

maker
0     B
1     E
2     A

# Задача 10

https://sql-ex.ru/exercises/index.php?act=learn&LN=10

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price

In [ ]:
sql = '''
select * from printer p
'''

In [ ]:
select(sql)

code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0
5     6  1288     n   Laser  400.0

In [ ]:
sql = '''
select model, price from printer
where price = (select MAX(price) from printer)
'''

In [ ]:
select(sql)

model  price
0  1276  400.0
1  1288  400.0

# Задача 11

https://sql-ex.ru/exercises/index.php?act=learn&LN=11

Найдите среднюю скорость ПК.

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''select distinct avg(speed) from PC

'''

In [ ]:
select(sql)

avg
0  608.333333

# Задача 12

https://sql-ex.ru/exercises/index.php?act=learn&LN=12


Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
sql = '''
select * from Laptop
'''

In [ ]:
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [ ]:
sql = '''
select avg(speed) from Laptop
where price > 1000
'''

In [ ]:
select(sql)

avg
0  700.0

# Задача 13

https://sql-ex.ru/exercises/index.php?act=learn&LN=13

Найдите среднюю скорость ПК, выпущенных производителем A.

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''select avg(speed) from PC
join Product p on pc.model = p.model
where p.Maker = 'A' 
'''

In [ ]:
select(sql)

avg
0  606.25

# Задача 14

https://sql-ex.ru/exercises/index.php?act=learn&LN=14

Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.

In [ ]:
sql = '''select * from Ships'''

In [ ]:
select(sql)

name           class  launched
0        California       Tennessee      1921
1            Haruna           Kongo      1916
2              Hiei           Kongo      1914
3              Iowa            Iowa      1943
4         Kirishima           Kongo      1915
5             Kongo           Kongo      1913
6          Missouri            Iowa      1944
7           Musashi          Yamato      1942
8        New Jersey            Iowa      1943
9    North Carolina  North Carolina      1941
10        Ramillies         Revenge      1917
11           Renown          Renown      1916
12          Repulse          Renown      1916
13       Resolution          Renown      1916
14          Revenge         Revenge      1916
15        Royal Oak         Revenge      1916
16  Royal Sovereign         Revenge      1916
17        Tennessee       Tennessee      1920
18       Washington  North Carolina      1941
19        Wisconsin            Iowa      1944
20           Yamato          Yamato      1941
21     South Dakota  North Carolina      1941

In [ ]:
sql = '''select s.class, s.name, c.country from Ships s
join Classes c on s.class = c.class
where numguns >= 10
'''

In [ ]:
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

# Задача 15

https://sql-ex.ru/exercises/index.php?act=learn&LN=15

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''select distinct hd from PC
group by hd
having count(model) >= 2

'''

In [ ]:
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

# Задача 16

https://sql-ex.ru/exercises/index.php?act=learn&LN=16

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.

In [ ]:
sql = '''select * from PC'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''
select distinct p1.model, p2.model, p1.speed, p1.ram from pc p1, pc p2
where p1.speed = p2.speed and p1.ram = p2.ram and p1.model > p2.model
'''

In [ ]:
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

# Задача 17

https://sql-ex.ru/exercises/index.php?act=learn&LN=17

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed

In [ ]:
sql = '''select * from Laptop'''

In [ ]:
select(sql)

code model  speed  ram    hd   price  screen
0     1  1298    350   32   4.0   700.0      11
1     2  1321    500   64   8.0   970.0      12
2     3  1750    750  128  12.0  1200.0      14
3     4  1298    600   64  10.0  1050.0      15
4     5  1752    750  128  10.0  1150.0      14
5     6  1298    450   64  10.0   950.0      12

In [ ]:
select distinct p.type,p.model,l.speed
from laptop l
join product p on l.model=p.model
where l.speed<(select min(speed)
                      from pc) 

In [ ]:
sql = '''select distinct p.type, l.model, l.speed from Laptop l
join Product p on l.model = p.model
where l.speed < (select min(pc.speed) from PC)

'''

In [ ]:
select(sql)

type model  speed
0  Laptop  1298    350

# Задача 18

https://sql-ex.ru/exercises/index.php?act=learn&LN=18

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [ ]:
sql = '''select * from Printer'''

In [ ]:
select(sql)

code model color    type  price
0     1  1276     n   Laser  400.0
1     2  1433     y     Jet  270.0
2     3  1434     y     Jet  290.0
3     4  1401     n  Matrix  150.0
4     5  1408     n  Matrix  270.0
5     6  1288     n   Laser  400.0

In [ ]:
sql = '''select distinct t.maker, p.price from Product t
join Printer p on t.model = p.model
where p.price = (select min(p.price) from Printer p where p.color = 'y') 
and color = 'y'
'''

In [ ]:
select(sql)

maker  price
0     D  270.0

# Задача 19

https://sql-ex.ru/exercises/index.php?act=learn&LN=19

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [ ]:
sql = '''select * from Product limit 5 '''

In [ ]:
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [ ]:
sql = '''select distinct t.maker, 
avg(l.screen) over (partition by maker) 
from Product t
join Laptop l on t.model = l.model
'''

In [ ]:
select(sql)

maker   avg
0     C  12.0
1     B  14.0
2     A  13.0

# Задача 20

https://sql-ex.ru/exercises/index.php?act=learn&LN=20

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [ ]:
sql = '''select * from Product limit 5'''

In [ ]:
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [ ]:
sql = '''
with cn as
(select p.maker, count(p.model) over (partition by maker) as cnt from Product p
where type = 'PC')

select distinct * from cn
where cnt > 2
'''

In [ ]:
select(sql)

maker  cnt
0     E    3

# Задача 21

https://sql-ex.ru/exercises/index.php?act=learn&LN=21

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [ ]:
sql = '''select * from PC limit 5'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [ ]:
sql = '''select distinct p.maker, max(pc.price) over (partition by maker) from Product p
join PC on p.model = pc.model
'''

In [ ]:
select(sql)

maker    max
0     B  850.0
1     A  980.0
2     E  350.0

# Задача 22

https://sql-ex.ru/exercises/index.php?act=learn&LN=22

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [ ]:
sql = '''select * from PC '''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0      1  1232    500   64   5.0  12x  600.0
1      2  1121    750  128  14.0  40x  850.0
2      3  1233    500   64   5.0  12x  600.0
3      4  1121    600  128  14.0  40x  850.0
4      5  1121    600  128   8.0  40x  850.0
5      6  1233    750  128  20.0  50x  950.0
6      7  1232    500   32  10.0  12x  400.0
7      8  1232    450   64   8.0  24x  350.0
8      9  1232    450   32  10.0  24x  350.0
9     10  1260    500   32  10.0  12x  350.0
10    11  1233    900  128  40.0  40x  980.0
11    12  1233    800  128  20.0  50x  970.0

In [ ]:
sql = '''
select speed, avg(price) as price from PC
where speed > 600
group by speed
'''

In [ ]:
select(sql)

speed
0    900
1    750
2    800

# Задача 23

https://sql-ex.ru/exercises/index.php?act=learn&LN=23

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker

In [ ]:
sql = '''select * from PC limit 5'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [ ]:
sql = '''
SELECT DISTINCT maker
FROM product t1 JOIN pc t2 ON t1.model=t2.model
WHERE speed>=750 AND maker IN
( SELECT maker
FROM product t1 JOIN laptop t2 ON t1.model=t2.model
WHERE speed>=750 )
'''

In [ ]:
sql = '''
select distinct p.maker from Product p
join PC on p.model = pc.model
where pc.speed >= 750 
union
select p.maker from Product p
join Laptop l on p.model = l.model
where l.speed >= 750


'''

In [ ]:
select(sql)

maker
0     B
1     A

# Задача 24

https://sql-ex.ru/exercises/index.php?act=learn&LN=24

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [ ]:
sql = '''select count(*) from Laptop
union 
select count(*) from PC
'''

In [ ]:
select(sql)

count
0      6
1     12

In [ ]:
sql = '''
with maxpr as
(select pc.model, pc.price from PC
union
select l.model, l.price from Laptop l
union
select p.model, p.price from Printer p)

select mpr.model from maxpr mpr
where mpr.price = (select max(mpr.price) from maxpr mpr)

'''

In [ ]:
select(sql)

model
0  1750

# Задача 25

https://sql-ex.ru/exercises/index.php?act=learn&LN=25

Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker

In [ ]:
sql = '''select * from Product limit 5'''

In [ ]:
select(sql)

maker model     type
0     B  1121       PC
1     A  1232       PC
2     A  1233       PC
3     E  1260       PC
4     A  1276  Printer

In [ ]:
sql = '''
select distinct p.maker from Product p
where p.model in (
  select pc.model from PC pc
  where pc.ram = (select min(pc.ram) from pc) 
  and pc.speed = (
    select max(pc.speed) from PC
    where pc.ram = (select min(pc.ram) from PC)
  ))
and p.maker in (
  select p.maker from Product p
  where p.type = 'Printer'
)

'''

In [ ]:
select(sql)

maker
0     A
1     E

# Задача 26

https://sql-ex.ru/exercises/index.php?act=learn&LN=26

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.

In [ ]:
sql = '''select * from PC limit 5'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [ ]:
sql = '''
with LapPC as (
  select pc.model, pc.price from PC
  where pc.model in (select p.model from Product p
  where p.maker = 'A' and p.type not in ('Printer'))
  union all
  select l.model, l.price from Laptop l
  where l.model in (select p.model from Product p
  where p.maker = 'A' and p.type not in ('Printer'))
)
select avg(price) as AVG_price from LapPC
'''

In [ ]:
select(sql)

avg_price
0  754.166667

# Задача 27

https://sql-ex.ru/exercises/index.php?act=learn&LN=27

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [ ]:
sql = '''select * from PC limit 5'''

In [ ]:
select(sql)

code model  speed  ram    hd   cd  price
0     1  1232    500   64   5.0  12x  600.0
1     2  1121    750  128  14.0  40x  850.0
2     3  1233    500   64   5.0  12x  600.0
3     4  1121    600  128  14.0  40x  850.0
4     5  1121    600  128   8.0  40x  850.0

In [ ]:
sql = '''
SELECT product.maker, AVG(pc.hd) FROM pc, product 
WHERE product.model = pc.model
AND product.maker IN ( SELECT DISTINCT maker FROM product
WHERE product.type = 'printer')
GROUP BY maker

'''

In [ ]:
select(sql)

Empty DataFrame
Columns: [maker, avg]
Index: []

# Задача 28

https://sql-ex.ru/exercises/index.php?act=learn&LN=28

Используя таблицу Product, определить количество производителей, выпускающих по одной модели.

In [ ]:
sql = '''
select * from Product p 
'''

In [ ]:
select(sql)

maker model     type
0      B  1121       PC
1      A  1232       PC
2      A  1233       PC
3      E  1260       PC
4      A  1276  Printer
5      D  1288  Printer
6      A  1298   Laptop
7      C  1321   Laptop
8      A  1401  Printer
9      A  1408  Printer
10     D  1433  Printer
11     E  1434  Printer
12     B  1750   Laptop
13     A  1752   Laptop
14     E  2113       PC
15     E  2112       PC

In [ ]:
sql = '''
with qty as (
select p.maker, count(p.model) as cnt from Product p 
group by p.maker
having count(p.model) = 1
)

select count(qty.maker) as cnt from qty

'''

In [ ]:
select(sql)

cnt
0    1

# Задача 29

https://sql-ex.ru/exercises/index.php?act=learn&LN=29

В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.

In [ ]:
sql = '''
select * from Outcome_o limit 5
'''

In [ ]:
select(sql)

point       date      out
0      1 2001-03-14  15348.0
1      1 2001-03-24   3663.0
2      1 2001-03-26   1221.0
3      1 2001-03-28   2075.0
4      1 2001-03-29   2004.0

In [ ]:
sql = '''
SELECT t1.point, t1.date, inc, out
FROM income_o t1 LEFT JOIN outcome_o t2 ON t1.point = t2.point
AND t1.date = t2.date
UNION
SELECT t2.point, t2.date, inc, out
FROM income_o t1 RIGHT JOIN outcome_o t2 ON t1.point = t2.point
AND t1.date = t2.date
'''

In [ ]:
select(sql)

point       date      inc       out
0       3 2001-09-14      NaN   2300.00
1       1 2001-04-11      NaN   3195.04
2       2 2001-03-22  10000.0   1440.00
3       3 2001-10-02  18000.0       NaN
4       1 2001-03-26      NaN   1221.00
5       1 2001-03-28      NaN   2075.00
6       2 2001-04-02      NaN   2040.00
7       2 2001-03-29      NaN   7848.00
8       1 2001-05-11   4500.0   2530.00
9       1 2001-03-29      NaN   2004.00
10      1 2001-04-27      NaN   3110.00
11      3 2002-09-16      NaN   2150.00
12      1 2001-04-13   5000.0   4490.00
13      1 2001-03-23  15000.0       NaN
14      1 2001-03-22  15000.0       NaN
15      2 2001-03-24   1500.0       NaN
16      1 2001-03-24   3400.0   3663.00
17      3 2001-09-13  11500.0   1500.00
18      1 2001-03-14      NaN  15348.00

# Задача 30

https://sql-ex.ru/exercises/index.php?act=learn&LN=30

В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL).

In [ ]:
sql = '''select * from outcome limit 5'''

In [ ]:
select(sql)

code  point       date      out
0     1      1 2001-03-14  15348.0
1     2      1 2001-03-24   3663.0
2     3      1 2001-03-26   1221.0
3     4      1 2001-03-28   2075.0
4     5      1 2001-03-29   2004.0

In [ ]:
sql = '''select tc.point, tc.date, out, inc from Outcome tc
left join Income nc on tc.code = nc.code

'''

In [ ]:
select(sql)

point       date       out      inc
0       1 2001-03-14  15348.00  15000.0
1       1 2001-03-24   3663.00  15000.0
2       1 2001-03-26   1221.00   3600.0
3       1 2001-03-28   2075.00  10000.0
4       1 2001-03-29   2004.00   1500.0
5       1 2001-04-11   3195.04   5000.0
6       1 2001-04-13   4490.00   4500.0
7       1 2001-04-27   3110.00  15000.0
8       1 2001-05-11   2530.00   1500.0
9       2 2001-03-22   1440.00   5000.0
10      2 2001-03-29   7848.00   3400.0
11      2 2001-04-02   2040.00   1350.0
12      1 2001-03-24   3500.00   1750.0
13      2 2001-03-22   1440.00      NaN
14      1 2001-03-29   2006.00      NaN
15      3 2001-09-13   1200.00      NaN
16      3 2001-09-13   1500.00      NaN
17      3 2001-09-14   1150.00      NaN